kevin-lee/refined4s

modules/refined4s-core/shared/src/main/scala/refined4s/Refined.scala
modules/refined4s-core/shared/src/test/scala/refined4s/RefinedSpec.scala

Close #1 - Add `Refined[A]`

---

modules/refined4s-core/shared/src/test/scala/refined4s/RefinedSpec.scala

Issue #1 - Add test for Refined.unapply

Issue #1 - Add test for Refined.unapply

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/task-template.yml

Add: GitHub Actions - templates for the task and bug tickets

Add: GitHub Actions - templates for the task and bug tickets

---

modules/refined4s-core/shared/src/main/scala/refined4s/numeric.scala

Close #11 - [core] Add `numeric.Numeric`

Close #11 - [core] Add `numeric.Numeric`

---

modules/refined4s-core/shared/src/main/scala/refined4s/numeric.scala
modules/refined4s-core/shared/src/test/scala/refined4s/numericSpec.scala

Close #10 - [core] Add `numeric.NonNegInt`

Close #10 - [core] Add `numeric.NonNegInt`

---

modules/refined4s-core/shared/src/main/scala/refined4s/numeric.scala
modules/refined4s-core/shared/src/test/scala/refined4s/numericSpec.scala

Close #9 - [core] Add `numeric.PosInt`

Close #9 - [core] Add `numeric.PosInt`

---

modules/refined4s-core/shared/src/main/scala/refined4s/numeric.scala
modules/refined4s-core/shared/src/test/scala/refined4s/numericSpec.scala

Close #8 - [core] Add `numeric.NonPosInt`

Close #8 - [core] Add `numeric.NonPosInt`

---

modules/refined4s-core/shared/src/main/scala/refined4s/Refined.scala
modules/refined4s-core/shared/src/main/scala/refined4s/numeric.scala
modules/refined4s-core/shared/src/main/scala/refined4s/strings.scala
modules/refined4s-core/shared/src/test/scala/refined4s/numericSpec.scala
modules/refined4s-core/shared/src/test/scala/refined4s/stringsSpec.scala

Update: Error messages

---

modules/refined4s-core/shared/src/main/scala/refined4s/numeric.scala
modules/refined4s-core/shared/src/test/scala/refined4s/numericSpec.scala

Close #18 - [core] Add `numeric.NegLong`

Close #18 - [core] Add `numeric.NegLong`

---

modules/refined4s-core/shared/src/main/scala/refined4s/numeric.scala
modules/refined4s-core/shared/src/test/scala/refined4s/numericSpec.scala

Close #19 - [core] Add `numeric.NonNegLong`

Close #19 - [core] Add `numeric.NonNegLong`

---

modules/refined4s-core/shared/src/main/scala/refined4s/numeric.scala
modules/refined4s-core/shared/src/test/scala/refined4s/numericSpec.scala

Close #20 - [core] Add `numeric.PosLong`

Close #20 - [core] Add `numeric.PosLong`

---

modules/refined4s-core/shared/src/main/scala/refined4s/numeric.scala
modules/refined4s-core/shared/src/test/scala/refined4s/numericSpec.scala

Close #21 - [core] Add `numeric.NonPosLong`

Close #21 - [core] Add `numeric.NonPosLong`

---

modules/refined4s-core/shared/src/main/scala/refined4s/numeric.scala
modules/refined4s-core/shared/src/test/scala/refined4s/numericSpec.scala

Add more tests for `numeric.Numeric.numericToOrdered`

Add more tests for `numeric.Numeric.numericToOrdered`

---

codecov.yml

Add: `codecov.yml` - with PR comment layout

Add: `codecov.yml` - with PR comment layout

---

build.sbt
project/plugins.sbt

Bump `xuwei-k`'s `scalafix-rules` to `0.3.0`

Bump `xuwei-k`'s `scalafix-rules` to `0.3.0`

---

build.sbt
modules/refined4s-core/shared/src/main/scala/refined4s/RefinedBase.scala
modules/refined4s-core/shared/src/test/scala/refined4s/InlinedRefinedCatsSpec.scala
modules/refined4s-core/shared/src/test/scala/refined4s/InlinedRefinedType.scala
modules/refined4s-core/shared/src/test/scala/refined4s/RefinedCatsSpec.scala

Close #40 - Add `deriving` to derive type-class from the base type

Close #40 - Add `deriving` to derive type-class from the base type

---

modules/refined4s-core/shared/src/main/scala/refined4s/Newtype.scala
modules/refined4s-core/shared/src/main/scala/refined4s/NewtypeBase.scala
modules/refined4s-core/shared/src/test/scala/refined4s/NewtypeCatsSpec.scala
modules/refined4s-core/shared/src/test/scala/refined4s/NewtypeSpec.scala

Close #44 - Add `Newtype`

---

modules/refined4s-core/shared/src/main/scala/refined4s/RefinedBase.scala
modules/refined4s-core/shared/src/test/scala/refined4s/InlinedRefinedSpec.scala
modules/refined4s-core/shared/src/test/scala/refined4s/RefinedCtorSpec.scala
modules/refined4s-core/shared/src/test/scala/refined4s/RefinedSpec.scala

Close #51 - Add `RefinedCtor` type-class instance for `RefinedBase`

Close #51 - Add `RefinedCtor` type-class instance for `RefinedBase`

---

modules/refined4s-core/shared/src/test/scala/refined4s/numericSpec.scala

Fix test input for `numericSpec`

Fix test input for `numericSpec`

---

modules/refined4s-core/shared/src/main/scala/refined4s/numeric.scala
modules/refined4s-core/shared/src/test/scala/refined4s/numericSpec.scala

Close #67 - [core] Add `NegShort`, `NonNegShort`, `PosShort` and `NonPosShort` to numeric package

Close #67 - [core] Add `NegShort`, `NonNegShort`, `PosShort` and `NonPosShort` to numeric package

---

.scalafmt.conf

Bump scalafmt to 3.7.17

---

.github/workflows/release.yml

GitHub Actions - `release.yml`: Add `SBT_OPTS`

GitHub Actions - `release.yml`: Add `SBT_OPTS`

---

build.sbt

Turn off significant indentation

Turn off significant indentation

---

.scalafmt.conf

Update: scalafmt config: `maxColumn` `120` => `140`

Update: scalafmt config: `maxColumn` `120` => `140`

---

.github/workflows/build.yml
project/plugins.sbt

GitHub Actions: Add more Scala 3 build
Now it has builds for
- Scala 3.1.3
- Scala 3.2.2
- Scala 3.3.1

GitHub Actions: Add more Scala 3 build

---

codecov.yml
modules/refined4s-core/shared/src/main/scala/refined4s/internal/numericTools.scala
modules/refined4s-core/shared/src/main/scala/refined4s/numeric.scala
modules/refined4s-core/shared/src/test/scala/refined4s/numericSpec.scala

Close #79 - [core] Add `NegBigInt`, `NonNegBigInt`, `PosBigInt` and `NonPosBigInt` to `numeric` package

Close #79 - [core] Add `NegBigInt`, `NonNegBigInt`, `PosBigInt` and `NonPosBigInt` to `numeric` package

---

modules/refined4s-core/shared/src/main/scala/refined4s/internal/numericTools.scala
modules/refined4s-core/shared/src/main/scala/refined4s/numeric.scala
modules/refined4s-core/shared/src/test/scala/refined4s/numericSpec.scala

Close #83 - [core] Add `NegBigDecimal`, `NonNegBigDecimal`, `PosBigDecimal` and `NonPosBigDecimal` to `numeric` package

Close #83 - [core] Add `NegBigDecimal`, `NonNegBigDecimal`, `PosBigDecimal` and `NonPosBigDecimal` to `numeric` package

---

modules/refined4s-core/shared/src/main/scala/refined4s/network.scala
modules/refined4s-core/shared/src/test/scala/refined4s/networkSpec.scala

Close #85 - [core] Add `Uri` to `network` package

Close #85 - [core] Add `Uri` to `network` package

---

modules/refined4s-core/shared/src/main/scala/refined4s/types/network.scala
modules/refined4s-core/shared/src/main/scala/refined4s/types/numeric.scala
modules/refined4s-core/shared/src/main/scala/refined4s/types/strings.scala
modules/refined4s-core/shared/src/test/scala/refined4s/types/networkSpec.scala
modules/refined4s-core/shared/src/test/scala/refined4s/types/numericSpec.scala
modules/refined4s-core/shared/src/test/scala/refined4s/types/stringsSpec.scala

Close #87 - Add types package and move numeric, strings and network to it

Close #87 - Add types package and move numeric, strings and network to it

---

modules/refined4s-core/shared/src/main/scala/refined4s/types/all.scala

Close #89 - Add `all` package to `refined4s.types` and make it contain all packages in the `types` package

Close #89 - Add `all` package to `refined4s.types` and make it contain all packages in the `types` package

---

build.sbt

Enable `DevOopsGitHubReleasePlugin`

Enable `DevOopsGitHubReleasePlugin`

---

build.sbt

Properly set up the config for publishing to the Maven Central

Properly set up the config for publishing to the Maven Central

---

modules/refined4s-cats/shared/src/main/scala/refined4s/modules/cats/derivation/CatsEq.scala
modules/refined4s-cats/shared/src/main/scala/refined4s/modules/cats/derivation/CatsEqShow.scala
modules/refined4s-cats/shared/src/main/scala/refined4s/modules/cats/derivation/CatsShow.scala
modules/refined4s-cats/shared/src/main/scala/refined4s/modules/cats/syntax.scala
modules/refined4s-cats/shared/src/test/scala/refined4s/modules/cats/derivation/CatsEqShowSpec.scala
modules/refined4s-cats/shared/src/test/scala/refined4s/modules/cats/derivation/CatsEqSpec.scala
modules/refined4s-cats/shared/src/test/scala/refined4s/modules/cats/derivation/CatsShowSpec.scala
modules/refined4s-cats/shared/src/test/scala/refined4s/modules/cats/syntaxSpec.scala

Close #94 - Rename `refined4s.cats` to `refined4s.modules.cats`

Close #94 - Rename `refined4s.cats` to `refined4s.modules.cats`

---

modules/refined4s-cats/shared/src/main/scala/refined4s/modules/cats/derivation/instances.scala
modules/refined4s-cats/shared/src/test/scala/refined4s/modules/cats/derivation/instancesSpec.scala

Close #95 - Add `Eq[A]` and `Show[A]` instances for the existing refined types

Close #95 - Add `Eq[A]` and `Show[A]` instances for the existing refined types

---

build.sbt

Close #101 - Add `refined4s-circe` module to support circe

Close #101 - Add `refined4s-circe` module to support circe

---

modules/refined4s-circe/shared/src/main/scala/refined4s/modules/circe/derivation/instances.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/existingTypesSpec.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/instancesSpec.scala

Close #103 - [`refined4s-circe`] Add `Encoder` and `Decoder`s for `Newtype`, `Refined` and `InlinedRefined` with `Coercible` and `RefinedCtor`

Close #103 - [`refined4s-circe`] Add `Encoder` and `Decoder`s for `Newtype`, `Refined` and `InlinedRefined` with `Coercible` and `RefinedCtor`

---

modules/refined4s-core/shared/src/main/scala/refined4s/types/network.scala
modules/refined4s-core/shared/src/test/scala/refined4s/types/networkGens.scala
modules/refined4s-core/shared/src/test/scala/refined4s/types/networkSpec.scala

Close #110 - [`refined4s-core`] Add `PortNumber`, `SystemPortNumber`, `NonSystemPortNumber`, `UserPortNumber` and `DynamicPortNumber`

Close #110 - [`refined4s-core`] Add `PortNumber`, `SystemPortNumber`, `NonSystemPortNumber`, `UserPortNumber` and `DynamicPortNumber`

---

build.sbt

Close #112 - Add `refined4s-pureconfig` module to support `pureconfig`

Close #112 - Add `refined4s-pureconfig` module to support `pureconfig`

---

modules/refined4s-pureconfig/shared/src/main/scala/refined4s/modules/pureconfig/derivation/PureconfigConfigWriter.scala
modules/refined4s-pureconfig/shared/src/test/scala/refined4s/modules/pureconfig/derivation/PureconfigConfigWriterSpec.scala

Close #118 - [`refined4s-pureconfig`] Add `PureconfigConfigWriter` to provider `ConfigWriter` for `Newtype`, `Refined` and `InlinedRefined`

Close #118 - [`refined4s-pureconfig`] Add `PureconfigConfigWriter` to provider `ConfigWriter` for `Newtype`, `Refined` and `InlinedRefined`

---

modules/refined4s-pureconfig/shared/src/test/scala/refined4s/modules/pureconfig/derivation/PureconfigConfigReaderSpec.scala

Update: test input code from `Gen.unicode` to `Gen.alphaNum`

Update: test input code from `Gen.unicode` to `Gen.alphaNum`

---

modules/refined4s-doobie-ce2/shared/src/main/scala/refined4s/modules/doobie/derivation/instances.scala
modules/refined4s-doobie-ce2/shared/src/test/resources/logback.xml
modules/refined4s-doobie-ce2/shared/src/test/scala/extras/doobie/AutoDeletingFile.scala
modules/refined4s-doobie-ce2/shared/src/test/scala/extras/doobie/RunWithDb.scala
modules/refined4s-doobie-ce2/shared/src/test/scala/extras/runner/RunSync.scala
modules/refined4s-doobie-ce2/shared/src/test/scala/extras/runner/ce2/RunSyncCe2.scala
modules/refined4s-doobie-ce2/shared/src/test/scala/refined4s/modules/doobie/derivation/Example.scala
modules/refined4s-doobie-ce2/shared/src/test/scala/refined4s/modules/doobie/derivation/Gens.scala
modules/refined4s-doobie-ce2/shared/src/test/scala/refined4s/modules/doobie/derivation/instancesSpec.scala
modules/refined4s-doobie-ce3/shared/src/main/scala/refined4s/modules/doobie/derivation/instances.scala
modules/refined4s-doobie-ce3/shared/src/test/resources/logback.xml
modules/refined4s-doobie-ce3/shared/src/test/scala/extras/doobie/AutoDeletingFile.scala
modules/refined4s-doobie-ce3/shared/src/test/scala/extras/doobie/RunWithDb.scala
modules/refined4s-doobie-ce3/shared/src/test/scala/refined4s/modules/doobie/derivation/Example.scala
modules/refined4s-doobie-ce3/shared/src/test/scala/refined4s/modules/doobie/derivation/Gens.scala
modules/refined4s-doobie-ce3/shared/src/test/scala/refined4s/modules/doobie/derivation/instancesSpec.scala

Close #124 - [`refined4s-doobie`] Add `Get`s and `Put` for `Newtype`, `Refined` and `InlinedRefined` with `Coercible` and `RefinedCtor`

Close #124 - [`refined4s-doobie`] Add `Get`s and `Put` for `Newtype`, `Refined` and `InlinedRefined` with `Coercible` and `RefinedCtor`

---

modules/refined4s-circe/shared/src/main/scala/refined4s/modules/circe/derivation/CirceNewtypeCodec.scala
modules/refined4s-circe/shared/src/main/scala/refined4s/modules/circe/derivation/CirceRefinedCodec.scala

Remove unnecessary context bound

Remove unnecessary context bound

---

docs/core/refined/_category_.json
docs/core/refined/refined.md
docs/core/refined/types.md

Update docs: add refined - `refined.md` and `types.md`: pre-defined refined types

Update docs: add refined - `refined.md` and `types.md`: pre-defined refined types

---

docs/core/refined/custom-type.md

Update docs: `custom-type.md`: Add custom refined types

Update docs: `custom-type.md`: Add custom refined types

---

website/docusaurus.config.ts

Update docs: `docusaurus.config.ts` - Docusaurus config to change the code block theme and handle potential Algolia and Google Analytics configs

Update docs: `docusaurus.config.ts` - Docusaurus config to change the code block theme and handle potential Algolia and Google Analytics configs

---

website/docusaurus.config.ts

Update docs: `docusaurus.config.ts` - Fix the broken function to check if an object is empty

Update docs: `docusaurus.config.ts` - Fix the broken function to check if an object is empty

---

docs/cats/_category_.json
docs/cats/cats.md

Update docs: Add doc for the `refined4s-cats` module

Update docs: Add doc for the `refined4s-cats` module

---

website/src/css/custom.css

Update docs: Change the width of the doc page to 80%

Update docs: Change the width of the doc page to 80%

---

docs/circe/_category_.json
docs/circe/circe.md
docs/doobie/_category_.json
docs/doobie/doobie.md
docs/pureconfig/_category_.json
docs/pureconfig/pureconfig.md

Update docs: Add docs for the rest of modules (incomplete)
- circe
- pureconfig
- doobie

Update docs: Add docs for the rest of modules (incomplete)

---

docs/cats/cats.md

Update docs: Add more to `cats.md`

Update docs: Add more to `cats.md`

---

docs/core/refined/types.md

Update docs: Add pre-defined `Long` types - `types.md`

Update docs: Add pre-defined `Long` types - `types.md`

---

build.sbt
modules/refined4s-cats/shared/src/test/scala/refined4s/modules/cats/derivation/CatsEqShowSpec.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/CirceCodecSpec.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/CirceDecoderSpec.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/CirceEncoderSpec.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/instancesSpec.scala
modules/refined4s-core/shared/src/main/scala/refined4s/RefinedBase.scala
modules/refined4s-core/shared/src/main/scala/refined4s/types/numeric.scala
modules/refined4s-core/shared/src/test/scala/refined4s/InlinedRefinedType.scala
modules/refined4s-core/shared/src/test/scala/refined4s/types/networkSpec.scala
modules/refined4s-doobie-ce2/shared/src/main/scala/refined4s/modules/doobie/derivation/DoobieNewtypeGetPut.scala
modules/refined4s-doobie-ce2/shared/src/main/scala/refined4s/modules/doobie/derivation/DoobieRefinedGetPut.scala
modules/refined4s-doobie-ce2/shared/src/main/scala/refined4s/modules/doobie/derivation/instances.scala
modules/refined4s-doobie-ce2/shared/src/test/scala/refined4s/modules/doobie/derivation/DoobieGetPutSpec.scala
modules/refined4s-doobie-ce2/shared/src/test/scala/refined4s/modules/doobie/derivation/instancesSpec.scala
modules/refined4s-doobie-ce3/shared/src/main/scala/refined4s/modules/doobie/derivation/DoobieNewtypeGetPut.scala
modules/refined4s-doobie-ce3/shared/src/main/scala/refined4s/modules/doobie/derivation/DoobieRefinedGetPut.scala
modules/refined4s-doobie-ce3/shared/src/main/scala/refined4s/modules/doobie/derivation/instances.scala
modules/refined4s-doobie-ce3/shared/src/test/scala/refined4s/modules/doobie/derivation/DoobieGetPutSpec.scala
modules/refined4s-doobie-ce3/shared/src/test/scala/refined4s/modules/doobie/derivation/instancesSpec.scala
modules/refined4s-pureconfig/shared/src/test/scala/refined4s/modules/pureconfig/derivation/PureconfigConfigReaderSpec.scala
modules/refined4s-pureconfig/shared/src/test/scala/refined4s/modules/pureconfig/derivation/PureconfigConfigWriterSpec.scala
modules/refined4s-pureconfig/shared/src/test/scala/refined4s/modules/pureconfig/derivation/existingTypesSpec.scala
modules/refined4s-pureconfig/shared/src/test/scala/refined4s/modules/pureconfig/derivation/instancesSpec.scala
project/plugins.sbt

Bump sbt plugins
- sbt-docusaur to 0.15.0
- sbt-devoops to 3.0.0
- sbt-tpolecat to 0.5.0
Also clean up unused code

Bump sbt plugins

---

modules/refined4s-doobie-ce2/shared/src/main/scala/refined4s/modules/doobie/derivation/instances.scala
modules/refined4s-doobie-ce3/shared/src/main/scala/refined4s/modules/doobie/derivation/instances.scala

Close #156 - [`refined4s-doobie`] Make type-classes in `refined4s.modules.doobie.derivation.instances` `inline`

Close #156 - [`refined4s-doobie`] Make type-classes in `refined4s.modules.doobie.derivation.instances` `inline`

---

modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/CirceCodecSpec.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/CirceDecoderSpec.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/CirceEncoderSpec.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/instancesSpec.scala
modules/refined4s-core/shared/src/main/scala/refined4s/InlinedRefined.scala
modules/refined4s-core/shared/src/main/scala/refined4s/types/network.scala
modules/refined4s-core/shared/src/main/scala/refined4s/types/numeric.scala
modules/refined4s-core/shared/src/test/scala/refined4s/InlinedRefinedSpec.scala
modules/refined4s-core/shared/src/test/scala/refined4s/InlinedRefinedType.scala
modules/refined4s-core/shared/src/test/scala/refined4s/types/networkSpec.scala
modules/refined4s-doobie-ce2/shared/src/test/scala/refined4s/modules/doobie/derivation/Example.scala
modules/refined4s-doobie-ce2/shared/src/test/scala/refined4s/modules/doobie/derivation/ExampleWithDoobieGetPut.scala
modules/refined4s-doobie-ce3/shared/src/test/scala/refined4s/modules/doobie/derivation/Example.scala
modules/refined4s-doobie-ce3/shared/src/test/scala/refined4s/modules/doobie/derivation/ExampleWithDoobieGetPut.scala
modules/refined4s-pureconfig/shared/src/test/scala/refined4s/modules/pureconfig/derivation/PureconfigConfigReaderSpec.scala
modules/refined4s-pureconfig/shared/src/test/scala/refined4s/modules/pureconfig/derivation/PureconfigConfigWriterSpec.scala
modules/refined4s-pureconfig/shared/src/test/scala/refined4s/modules/pureconfig/derivation/instancesSpec.scala

Close #158 - [`refined4s-core`] Improve compile-time error message for `inline apply` method

Close #158 - [`refined4s-core`] Improve compile-time error message for `inline apply` method

---

build.sbt
docs/cats/cats.md
docs/core/refined/types.md

Update docs: Add pre-defined `BigInt` types - `types.md`

Update docs: Add pre-defined `BigInt` types - `types.md`

---

modules/refined4s-cats/shared/src/main/scala/refined4s/modules/cats/derivation/instances.scala
modules/refined4s-doobie-ce2/shared/src/main/scala/refined4s/modules/doobie/derivation/instances.scala
modules/refined4s-doobie-ce3/shared/src/main/scala/refined4s/modules/doobie/derivation/instances.scala
modules/refined4s-pureconfig/shared/src/main/scala/refined4s/modules/pureconfig/derivation/PureconfigNewtypeConfigReader.scala
modules/refined4s-pureconfig/shared/src/main/scala/refined4s/modules/pureconfig/derivation/PureconfigRefinedConfigReader.scala

Close #165 - Rename derived type classes - some of them have a naming conflict issue

Close #165 - Rename derived type classes - some of them have a naming conflict issue

---

build.sbt
modules/refined4s-circe/shared/src/main/scala/refined4s/modules/circe/derivation/generic/auto.scala
modules/refined4s-circe/shared/src/main/scala/refined4s/modules/circe/derivation/types/all.scala
modules/refined4s-circe/shared/src/main/scala/refined4s/modules/circe/derivation/types/network.scala
modules/refined4s-circe/shared/src/main/scala/refined4s/modules/circe/derivation/types/numeric.scala
modules/refined4s-circe/shared/src/main/scala/refined4s/modules/circe/derivation/types/strings.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/CirceCodecWithInstancesSpec.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/generic/autoSpec.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/types/typesSpec.scala

Close #166 - [`refined4s-circe`] Add explicit `Encoder` and `Decoder` for pre-defined types

Close #166 - [`refined4s-circe`] Add explicit `Encoder` and `Decoder` for pre-defined types

---

modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/types/CirceCodecWithTypeClassesForTypesSpec.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/types/allSpec.scala

Renaming test objects

---

build.sbt
docs/cats/cats.md
docs/circe/circe.md
docs/doobie/doobie.md
docs/pureconfig/pureconfig.md

Update docs - with the latest version (`0.6.0`) and add the doc content for `circe.md`

Update docs - with the latest version (`0.6.0`) and add the doc content for `circe.md`

---

docs/pureconfig/pureconfig.md

Update docs - Add the doc content for `pureconfig.md`

Update docs - Add the doc content for `pureconfig.md`

---

docs/core/refined/types.md

* Add the doc content for `types.md` - with refined `Double` types
* Add the doc content for `types.md` - with refined `Float` types
* Add the doc content for `types.md` - with refined `BigDecimal` types
* Add the doc content for `types.md` - with refined `NonEmptyString` type
* Add the doc content for `types.md` - with refined `Uri` type

Update docs - Add the doc content for `types.md`

---

modules/refined4s-cats/shared/src/main/scala/refined4s/modules/cats/syntax.scala
modules/refined4s-cats/shared/src/test/scala/refined4s/modules/cats/syntaxSpec.scala

Close #184 - [`refined4s-cats`] Add `refinedNewtypeNel` in `refined4s.modules.cats.syntax`

Close #184 - [`refined4s-cats`] Add `refinedNewtypeNel` in `refined4s.modules.cats.syntax`

---

modules/refined4s-cats/shared/src/main/scala/refined4s/modules/cats/syntax.scala
modules/refined4s-cats/shared/src/test/scala/refined4s/modules/cats/syntaxSpec.scala

Close #190 - [`refined4s-cats`] Add `validateNelAs` in `refined4s.modules.cats.syntax` to validate and return `ValidatedNel`

Close #190 - [`refined4s-cats`] Add `validateNelAs` in `refined4s.modules.cats.syntax` to validate and return `ValidatedNel`

---

modules/refined4s-cats/shared/src/main/scala/refined4s/modules/cats/derivation/CatsOrder.scala
modules/refined4s-cats/shared/src/test/scala/refined4s/modules/cats/derivation/CatsOrderSpec.scala

Close #203 - [`refined4s-cats`] Add `CatsOrder`

Close #203 - [`refined4s-cats`] Add `CatsOrder`

---

README.md

Update: `README.md` - Replace the logo image with the new one

Update: `README.md` - Replace the logo image with the new one

---

docs/cats/_category_.json
docs/circe/_category_.json
docs/core/newtype-refined/_category_.json
docs/core/newtype-refined/newtype-refined.md
docs/doobie/_category_.json
docs/pureconfig/_category_.json

Update: docs - with `Newtype` + `Refined`

Update: docs - with `Newtype` + `Refined`

---

docs/core/newtype/newtype.md

Update docs: `newtype.md` - Add more example and pattern matching info

Update docs: `newtype.md` - Add more example and pattern matching info

---

docs/core/refined/custom-type.md

Update docs: `custom-type.md` - Add more example, get the actual value and the pattern matching info

Update docs: `custom-type.md` - Add more example, get the actual value and the pattern matching info

---

docs/core/newtype/newtype.md
docs/intro.md

Update docs: more info

---

docs/intro.md

Update docs: `intro.md` - Add "Why refined4s?"

Update docs: `intro.md` - Add "Why refined4s?"

---

build.sbt
modules/refined4s-extras-render/shared/src/main/scala/refined4s/modules/extras/derivation/ExtrasRender.scala
modules/refined4s-extras-render/shared/src/main/scala/refined4s/modules/extras/derivation/generic/auto.scala
modules/refined4s-extras-render/shared/src/main/scala/refined4s/modules/extras/derivation/types/all.scala
modules/refined4s-extras-render/shared/src/test/scala/refined4s/modules/extras/derivation/ExtrasRenderSpec.scala
modules/refined4s-extras-render/shared/src/test/scala/refined4s/modules/extras/derivation/generic/autoSpec.scala
modules/refined4s-extras-render/shared/src/test/scala/refined4s/modules/extras/derivation/types/allSpec.scala

Close #215 - Add `refined4s-extras-render` to support `Render` for `refined4s`

Close #215 - Add `refined4s-extras-render` to support `Render` for `refined4s`

---

.github/workflows/build.yml
.github/workflows/sbt-build-all.sh

Update: GitHub Actions config - with `SBT_OPTS` and `JVM_OPTS`

Update: GitHub Actions config - with `SBT_OPTS` and `JVM_OPTS`

---

build.sbt
modules/refined4s-extras-render/shared/src/test/scala/refined4s/modules/extras/derivation/ExtrasRenderSpec.scala

Close #220 - Release `refined4s-extras-render` module

Close #220 - Release `refined4s-extras-render` module

---

changelogs/0.10.0.md

* Release `refined4s-extras-render` module (#220)
* Add `refined4s-extras-render` to support `Render` for `refined4s` (#215)
```scala 3
refined4s.modules.extras.derivation.ExtrasRender
refined4s.modules.extras.derivation.types.all.given
refined4s.modules.extras.derivation.generic.auto.given
```
e.g.)
```scala 3
import extras.render.Render
import refined4s.types.all.*
import refined4s.modules.extras.derivation.types.all.given
val name = NonEmptyString("Kevin")
Render[NonEmptyString].render(name)
// String = Kevin
```
```scala 3
import extras.render.Render
import refined4s.Newtype
import refined4s.modules.extras.derivation.ExtrasRender
object Name extends Newtype[String], ExtrasRender[String]
val name = Name("Kevin")
Render[Name].render(name)
// String = Kevin
``` …

refined4s v0.10.0

---

build.sbt
docs/doobie/doobie.md

Update docs: `doobie.md`

---

docs/doobie/doobie.md

Update docs: `doobie.md` - with more doobie support info

Update docs: `doobie.md` - with more doobie support info

---

docs/intro.md

Update docs: `intro.md` - Add `refined4s-extras-render` info

Update docs: `intro.md` - Add `refined4s-extras-render` info

---

docs/intro.md

Update docs: Fix `intro.md`

---

docs/core/refined/types.md

Update docs: `types.md` - Add `Min` and `Max` Values

Update docs: `types.md` - Add `Min` and `Max` Values

---

docs/core/refined/types.md

Update docs: `types.md` - Reorganize headings

Update docs: `types.md` - Reorganize headings

---

modules/refined4s-core/shared/src/main/scala/refined4s/types/numeric.scala

Close #239 - [`refined4s-core`] Move `MinValue` and `MaxValue` from each `MinMax` to `Min` and `Max`

Close #239 - [`refined4s-core`] Move `MinValue` and `MaxValue` from each `MinMax` to `Min` and `Max`

---

codecov.yml
modules/refined4s-refined-compat-scala2/shared/src/main/scala-2/refined4s/compat/RefinedCompatAllTypes.scala
modules/refined4s-refined-compat-scala3/shared/src/main/scala-3/refined4s/compat/RefinedCompatAllTypes.scala

Close #243 - Add `RefinedCompatAllTypes` to `refined4s-refined-compat-scala2` and `refined4s-refined-compat-scala3`

Close #243 - Add `RefinedCompatAllTypes` to `refined4s-refined-compat-scala2` and `refined4s-refined-compat-scala3`

---

modules/refined4s-cats/shared/src/main/scala/refined4s/modules/cats/derivation/types/all.scala
modules/refined4s-cats/shared/src/test/scala/refined4s/modules/cats/derivation/types/allSpec.scala
modules/refined4s-circe/shared/src/main/scala/refined4s/modules/circe/derivation/types/network.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/types/allSpec.scala
modules/refined4s-core/shared/src/main/scala/refined4s/types/network.scala
modules/refined4s-core/shared/src/test/scala/refined4s/types/networkGens.scala
modules/refined4s-core/shared/src/test/scala/refined4s/types/networkSpec.scala
modules/refined4s-doobie-ce2/shared/src/main/scala/refined4s/modules/doobie/derivation/types/all.scala
modules/refined4s-doobie-ce2/shared/src/test/scala/refined4s/modules/doobie/derivation/types/allSpec.scala
modules/refined4s-doobie-ce3/shared/src/main/scala/refined4s/modules/doobie/derivation/types/all.scala
modules/refined4s-doobie-ce3/shared/src/test/scala/refined4s/modules/doobie/derivation/types/allSpec.scala
modules/refined4s-pureconfig/shared/src/main/scala/refined4s/modules/pureconfig/derivation/types/all.scala
modules/refined4s-pureconfig/shared/src/test/scala/refined4s/modules/pureconfig/derivation/types/allSpec.scala

Close #246 - [`refined4s-core`] Add `Url` to `refined4s.types.network` and the type-class instances for Url in the other modules

Close #246 - [`refined4s-core`] Add `Url` to `refined4s.types.network` and the type-class instances for Url in the other modules

---

modules/refined4s-extras-render/shared/src/main/scala/refined4s/modules/extras/derivation/types/all.scala
modules/refined4s-extras-render/shared/src/test/scala/refined4s/modules/extras/derivation/types/allSpec.scala

Close #246 - [`refined4s-core`] Add `Render[Url]`

Close #246 - [`refined4s-core`] Add `Render[Url]`

---

modules/refined4s-core/shared/src/main/scala/refined4s/types/network.scala
modules/refined4s-core/shared/src/test/scala/refined4s/types/networkSpec.scala

Close #251 - [`refined4s-core`] Add `Uri.apply(java.net.URI)`

Close #251 - [`refined4s-core`] Add `Uri.apply(java.net.URI)`

---

modules/refined4s-core/shared/src/main/scala/refined4s/types/network.scala
modules/refined4s-core/shared/src/test/scala/refined4s/types/networkSpec.scala

Close #252 - [`refined4s-core`] Add `Url.apply(java.net.URL)`

Close #252 - [`refined4s-core`] Add `Url.apply(java.net.URL)`

---

modules/refined4s-refined-compat-scala2/shared/src/main/scala-2/refined4s/compat/RefinedCompatAllTypes.scala

Close #255 - [`refined4s-refined-compat-scala2`] Add `Uri`, `Url` and `Uuid`

Close #255 - [`refined4s-refined-compat-scala2`] Add `Uri`, `Url` and `Uuid`

---

changelogs/0.13.0.md

* [`refined4s-core`] Add `Url` to `refined4s.types.network` and the type-class instances for `Url` in the other modules (#246)
***
* [`refined4s-core`] Add `Uuid` `String` which can be validated as `java.util.UUID` and the type-class instances for `Uuid` in the other modules (#248)
***
* [`refined4s-core`] Add `Uri.apply(java.net.URI)` (#251)
***
* [`refined4s-core`] Add `Url.apply(java.net.URL)` (#252)
***
* [`refined4s-refined-compat-scala2`] Add `Uri`, `Url` and `Uuid` (#255)

refined4s v0.13.0

---

docs/intro.md

Update docs: add dependency for Scala.js

Update docs: add dependency for Scala.js

---

website/package-lock.json
website/package.json

Upgrade Docusaurus to 3.1.1

---

website/docusaurus.config.ts

Update docs: Make the left sidebar hidable

Update docs: Make the left sidebar hidable

---

build.sbt

Close #272 - Add `refined4s-tapir` to support `tapir`

Close #272 - Add `refined4s-tapir` to support `tapir`

---

modules/refined4s-tapir/shared/src/main/scala/refined4s/modules/tapir/derivation/types/all.scala
modules/refined4s-tapir/shared/src/main/scala/refined4s/modules/tapir/derivation/types/network.scala
modules/refined4s-tapir/shared/src/main/scala/refined4s/modules/tapir/derivation/types/numeric.scala
modules/refined4s-tapir/shared/src/main/scala/refined4s/modules/tapir/derivation/types/strings.scala
modules/refined4s-tapir/shared/src/test/scala/refined4s/modules/tapir/derivation/types/allSpec.scala

Close #276 - [`refined4s-tapir`] Add `Schema`s for pre-defined refined types

Close #276 - [`refined4s-tapir`] Add `Schema`s for pre-defined refined types

---

modules/refined4s-tapir/shared/src/main/scala/refined4s/modules/tapir/derivation/generic/auto.scala
modules/refined4s-tapir/shared/src/test/scala/refined4s/modules/tapir/derivation/generic/autoSpec.scala

Close #278 - [`refined4s-tapir`] Add `Schema` type-class instances with auto deriving

Close #278 - [`refined4s-tapir`] Add `Schema` type-class instances with auto deriving

---

changelogs/0.14.0.md

* Add `refined4s-tapir` to support `tapir` (#272)
* [`refined4s-tapir`] Add `TapirNewtypeSchema` and `TapirRefinedSchema` to support `sttp.tapir.Schema` for `refined4s` (#273)
* [`refined4s-tapir`] Add `Schema`s for pre-defined refined types (#276)
* [`refined4s-tapir`] Add `Schema` type-class instances with auto deriving (#278)

refined4s v0.14.0

---

build.sbt
modules/refined4s-core/shared/src/main/scala/refined4s/types/strings.scala
modules/refined4s-core/shared/src/test/scala/refined4s/types/stringsSpec.scala

Close #281 - [`refined4s-core`] Add `NonBlankString` which can be neither all whitespace chars nor an empty String

Close #281 - [`refined4s-core`] Add `NonBlankString` which can be neither all whitespace chars nor an empty String

---

modules/refined4s-cats/shared/src/main/scala/refined4s/modules/cats/derivation/types/all.scala
modules/refined4s-cats/shared/src/test/scala/refined4s/modules/cats/derivation/types/allSpec.scala
modules/refined4s-core/shared/src/main/scala/refined4s/types/strings.scala

Close #283 - [`refined4s-cats`] Add `cats` support for `NonBlankString`

Close #283 - [`refined4s-cats`] Add `cats` support for `NonBlankString`

---

modules/refined4s-cats/shared/src/test/scala/refined4s/modules/cats/derivation/generic/autoSpec.scala
modules/refined4s-cats/shared/src/test/scala/refined4s/modules/cats/derivation/types/allSpec.scala

Issue #283 - Add missing tests

Issue #283 - Add missing tests

---

modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/generic/autoSpec.scala

Add missing tests for circe support with auto derivation

Add missing tests for circe support with auto derivation

---

modules/refined4s-core/shared/src/test/scala/refined4s/types/stringsSpec.scala

[`refined4s-core`] Fix tests for `NonBlankString`

[`refined4s-core`] Fix tests for `NonBlankString`

---

modules/refined4s-pureconfig/shared/src/test/scala/refined4s/modules/pureconfig/derivation/generic/autoSpec.scala
modules/refined4s-pureconfig/shared/src/test/scala/refined4s/modules/pureconfig/derivation/types/allSpec.scala

[`refined4s-pureconfig`] Fix tests

[`refined4s-pureconfig`] Fix tests

---

modules/refined4s-doobie-ce2/shared/src/main/scala/refined4s/modules/doobie/derivation/types/all.scala
modules/refined4s-doobie-ce2/shared/src/test/scala/refined4s/modules/doobie/derivation/types/allSpec.scala
modules/refined4s-doobie-ce3/shared/src/main/scala/refined4s/modules/doobie/derivation/types/all.scala
modules/refined4s-doobie-ce3/shared/src/test/scala/refined4s/modules/doobie/derivation/types/allSpec.scala

Close #286 - [`refined4s-doobie`] Add `doobie` support for `NonBlankString`

Close #286 - [`refined4s-doobie`] Add `doobie` support for `NonBlankString`

---

docs/intro.md

Update docs: Add refined4s-tapir to `getting started`

Update docs: Add refined4s-tapir to `getting started`

---

build.sbt
docs/tapir/_category_.json
docs/tapir/tapir.md

Update docs: Add a guide doc for `refined4s-tapir`

Update docs: Add a guide doc for `refined4s-tapir`

---

README.md

Update `README.md` - with `refined4s-extras-render` and `refined4s-tapir` info

Update `README.md` - with `refined4s-extras-render` and `refined4s-tapir` info

---

docs/extras-render/_category_.json
docs/extras-render/extras-render.md

Update docs: Add a guide doc for `refined4s-extras-render`

Update docs: Add a guide doc for `refined4s-extras-render`

---

changelogs/0.15.0.md

* [`refined4s-core`] Add `NonBlankString` which can be neither all whitespace chars nor an empty String (#281)
```scala 3
NonBlankString("")
// Invalid value: [""]. It must be not all whitespace non-empty String
NonBlankString(" ")
// Invalid value: [" "]. It must be not all whitespace non-empty String
NonBlankString("   ")
// Invalid value: ["   "]. It must be not all whitespace non-empty String
NonBlankString("\n")
// Invalid value: ["\n"]. It must be not all whitespace non-empty String
NonBlankString("\t")
// Invalid value: ["\t"]. It must be not all whitespace non-empty String
NonBlankString("\t\n")
// Invalid value: ["\t\n"]. It must be not all whitespace non-empty String
NonBlankString(" \t \n")
// Invalid value: [" \t \n"]. It must be not all whitespace non-empty String
```
* …

refined4s v0.15.0

---

.github/workflows/coverage.yml
.github/workflows/release.yml

GitHubActions: Add separate test coverage build (`coverage.yml`) with Codecov

GitHubActions: Add separate test coverage build (`coverage.yml`) with Codecov

---

docs/core/refined/types.md

Update docs: Add `Uuid` to `types.md`.

Update docs: Add `Uuid` to `types.md`

---

docs/core/refined/types.md

Update docs: Fix broken docs as mdoc is not generating correct failure result

Update docs: Fix broken docs as mdoc is not generating correct failure result

---

docs/core/refined/types.md

Update docs: Add `NonBlankString` to `types.md`

Update docs: Add `NonBlankString` to `types.md`

---

.github/workflows/build.yml
.github/workflows/checks.yml
.github/workflows/coverage.yml
.github/workflows/doc-site-build-only.yml
.github/workflows/doc-site-publish.yml
.github/workflows/release.yml
build.sbt
project/plugins.sbt

Close #319 - Bump Scala to 3.3.3, the latest Long-Term Support (LTS) version

Close #319 - Bump Scala to 3.3.3, the latest Long-Term Support (LTS) version

---

project/plugins.sbt

Bump `sbt-devoops` to 3.1.0

---

build.sbt

Close #320 - Add a module to support Chimney

Close #320 - Add a module to support Chimney

---

modules/refined4s-chimney/shared/src/main/scala/refined4s/modules/chimney/derivation/ChimneyNewtype.scala
modules/refined4s-chimney/shared/src/test/scala/refined4s/modules/chimney/derivation/ChimneyNewtypeSpec.scala

Close #326 - [`refined4s-chimney`] Add `refined4s.modules.chimney.derivation.ChimneyNewtype` for `Newtype` derivation for Chimney

Close #326 - [`refined4s-chimney`] Add `refined4s.modules.chimney.derivation.ChimneyNewtype` for `Newtype` derivation for Chimney

---

modules/refined4s-chimney/shared/src/main/scala/refined4s/modules/chimney/derivation/ChimneyRefined.scala
modules/refined4s-chimney/shared/src/test/scala/refined4s/modules/chimney/derivation/ChimneyRefinedSpec.scala
modules/refined4s-chimney/shared/src/test/scala/refined4s/modules/chimney/derivation/derivationSpec.scala

Close #327 - [`refined4s-chimney`] Add `refined4s.modules.chimney.derivation.ChimneyRefined` for `Refined` derivation for Chimney

Close #327 - [`refined4s-chimney`] Add `refined4s.modules.chimney.derivation.ChimneyRefined` for `Refined` derivation for Chimney

---

modules/refined4s-chimney/shared/src/main/scala/refined4s/modules/chimney/derivation/ChimneyNewtype.scala
modules/refined4s-chimney/shared/src/test/scala/refined4s/modules/chimney/derivation/ChimneyNewtypeSpec.scala

Close #340 - [`refined4s-chimney`] Add missing `Transformer` to unwrap value for `ChimneyNewtype`

Close #340 - [`refined4s-chimney`] Add missing `Transformer` to unwrap value for `ChimneyNewtype`

---

modules/refined4s-chimney/shared/src/main/scala/refined4s/modules/chimney/derivation/ChimneyRefined.scala
modules/refined4s-chimney/shared/src/test/scala/refined4s/modules/chimney/derivation/ChimneyRefinedSpec.scala

Close #341 - [`refined4s-chimney`] Add missing `Transformer` to unwrap value for `ChimneyRefined`

Close #341 - [`refined4s-chimney`] Add missing `Transformer` to unwrap value for `ChimneyRefined`

---

modules/refined4s-chimney/shared/src/test/scala/refined4s/modules/chimney/derivation/ChimneyRefinedSpec.scala

`ChimneyRefinedSpec`: Put test types in `TestTypes1`

`ChimneyRefinedSpec`: Put test types in `TestTypes1`

---

modules/refined4s-chimney/shared/src/main/scala/refined4s/modules/chimney/derivation/ChimneyNewtype.scala
modules/refined4s-chimney/shared/src/test/scala/refined4s/modules/chimney/derivation/ChimneyNewtypeSpec.scala

Close #346 - [`refined4s-chimney`] Add `PartialTransformer` to transform `Newtype[A]` to `Newtype[Refined[A]]` for `ChimneyNewtype`

Close #346 - [`refined4s-chimney`] Add `PartialTransformer` to transform `Newtype[A]` to `Newtype[Refined[A]]` for `ChimneyNewtype`

---

modules/refined4s-chimney/shared/src/main/scala/refined4s/modules/chimney/derivation/ChimneyRefined.scala
modules/refined4s-chimney/shared/src/test/scala/refined4s/modules/chimney/derivation/ChimneyRefinedSpec.scala

Close #342 - [`refined4s-chimney`] Add `PartialTransformer` to transform `Refined[A]` to `Newtype[Refined[A]]` for `ChimneyRefined`

Close #342 - [`refined4s-chimney`] Add `PartialTransformer` to transform `Refined[A]` to `Newtype[Refined[A]]` for `ChimneyRefined`

---

changelogs/0.18.0.md

* [`refined4s-chimney`] Add missing `Transformer` to unwrap value for `ChimneyNewtype` (#340)
```scala 3
import refined4s.*
import refined4s.modules.chimney.derivation.*
final case class Person(name: Person.Name)
object Person {
object Name extends Newtype[String], ChimneyNewtype[String]
}
final case class User(name: String)
import io.scalaland.chimney.*
import io.scalaland.chimney.dsl.*
val person = Person(Person.Name("Wade Wilson"))
val deadpool = person.transformInto[User] // This is currently not possible.
```
***
* [`refined4s-chimney`] Add missing `Transformer` to unwrap value for `ChimneyRefined` (#341)
```scala 3
import refined4s.*
import refined4s.modules.chimney.derivation.*
final case class Person(name: Person.NotEmptyStr)
object Person {
type NotEmptyStr …
```

refined4s v0.18.0

---

build.sbt
docs/chimney/_category_.json
docs/chimney/chimney.md
docs/intro.md

Update: docs with `refined4s-chimney` info

Update: docs with `refined4s-chimney` info

---

docs/chimney/_category_.json
docs/circe/_category_.json
docs/doobie/_category_.json
docs/extras-render/_category_.json
docs/pureconfig/_category_.json
docs/tapir/_category_.json

Update docs: update the doc structure

Update docs: update the doc structure

---

modules/refined4s-core/shared/src/main/scala/refined4s/types/network.scala
modules/refined4s-core/shared/src/test/scala/refined4s/types/networkSpec.scala

Close #356 - [`refined4s-core`] Add `toUrl` to `Uri`, and add `toUri` to `toUrl`

Close #356 - [`refined4s-core`] Add `toUrl` to `Uri`, and add `toUri` to `toUrl`

---

modules/refined4s-core/shared/src/main/scala/refined4s/types/network.scala
modules/refined4s-core/shared/src/test/scala/refined4s/types/networkSpec.scala

Close #358 - [`refined4s-core`] Add `toURL` to `Uri`, and add `toURI` to `toUrl`

Close #358 - [`refined4s-core`] Add `toURL` to `Uri`, and add `toURI` to `toUrl`

---

modules/refined4s-circe/shared/src/main/scala/refined4s/modules/circe/derivation/CirceKeyEncoder.scala
modules/refined4s-circe/shared/src/main/scala/refined4s/modules/circe/derivation/CirceNewtypeKeyCodec.scala
modules/refined4s-circe/shared/src/main/scala/refined4s/modules/circe/derivation/CirceNewtypeKeyDecoder.scala
modules/refined4s-circe/shared/src/main/scala/refined4s/modules/circe/derivation/CirceRefinedKeyCodec.scala
modules/refined4s-circe/shared/src/main/scala/refined4s/modules/circe/derivation/CirceRefinedKeyDecoder.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/CirceKeyCodecSpec.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/CirceKeyDecoderSpec.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/CirceKeyEncoderSpec.scala

Close #355 - [`refined4s-circe`] Add `KeyEncoder`, `KeyDecoder` and `KeyCodec` for `Newtype` and `Refined`

Close #355 - [`refined4s-circe`] Add `KeyEncoder`, `KeyDecoder` and `KeyCodec` for `Newtype` and `Refined`

---

website/.gitignore
website/package.json

Bump docusaurus to 3.5.2

---

modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/types/networkSpec.scala

Fix the names in the tests

---

modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/generic/autoSpec.scala

Enable missing tests

---

modules/refined4s-circe/shared/src/main/scala/refined4s/modules/circe/derivation/generic/auto.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/generic/CustomTypeSpec.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/generic/networkSpec.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/generic/numericSpec.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/generic/stringsSpec.scala

Close #369 - [`refined4s-circe`] Add `KeyEncoder` and `KeyDecoder` to `refined4s.modules.circe.derivation.generic.auto`

Close #369 - [`refined4s-circe`] Add `KeyEncoder` and `KeyDecoder` to `refined4s.modules.circe.derivation.generic.auto`

---

.github/workflows/build.yml
.github/workflows/checks.yml
.github/workflows/coverage.yml
.github/workflows/doc-site-build-only.yml
.github/workflows/doc-site-publish.yml
.github/workflows/release.yml
.gitignore
build.sbt

Close #376 - Update GitHub Actions: Update `javaOptions`

Close #376 - Update GitHub Actions: Update `javaOptions`

---

build.sbt

Close #379 - [`refined4s-refined-compat-scala2`] Bump Scala `2.12` to `2.12.16`

Close #379 - [`refined4s-refined-compat-scala2`] Bump Scala `2.12` to `2.12.16`

---

changelogs/0.19.0.md

Update the changelog for v0.19.0

Update the changelog for v0.19.0

---

.scalafmt.conf

Update `.scalafmt.conf`: version to `3.8.3`

Update `.scalafmt.conf`: version to `3.8.3`

---

project/build.properties

Bump sbt to 1.10.1

---

modules/refined4s-core/jvm/src/test/scala/refined4s/types/networkCompatSpec.scala

Add missing tests for `Uri.toURL`

Add missing tests for `Uri.toURL`

---

changelogs/1.1.0.md

* Add Scala.js support for `refined4s-chimney` (#387)

refined4s v1.1.0

---

.github/workflows/build.yml
.github/workflows/checks.yml
.github/workflows/coverage.yml
.github/workflows/doc-site-build-only.yml
.github/workflows/doc-site-publish.yml
.github/workflows/release.yml

Update: GitHub Actions with new actions/setup-java with its caching sbt and use sbt/setup-sbt

Update: GitHub Actions with new actions/setup-java with its caching sbt and use sbt/setup-sbt

---

project/build.properties

Bump sbt to 1.10.6

---

.github/workflows/doc-site-build-only.yml
.github/workflows/doc-site-publish.yml

Update: Update `actions/cache` to `v4`

Update: Update `actions/cache` to `v4`

---

website/src/components/HomepageFeatures/index.tsx

Update: Change description type from `JSX.Element` to `ReactNode` in `FeatureItem`

Update: Change description type from `JSX.Element` to `ReactNode` in `FeatureItem`

---

project/build.properties

Bump sbt to `1.10.11`

---

README.md
docs/latest/intro.md
docs/v0/intro.md
website/src/pages/index.tsx

Update: Add hit counter badge to README, intro, and index files

Update: Add hit counter badge to README, intro, and index files

---

.gitignore

Update .gitignore to add `metals.sbt`

Update .gitignore to add `metals.sbt`

---

website/package.json

Update: Upgrade Docusaurus to 3.7.0

Update: Upgrade Docusaurus to 3.7.0

---

project/build.properties

Bump sbt to 1.11.1

---

project/plugins.sbt

Bump `sbt-devoops` to `3.2.0`

---

build.sbt

Close #424: Bump extras to `0.46.1`

Close #424: Bump extras to `0.46.1`

---

changelogs/1.4.0.md

* Support `Scala.js` again (#434)

refined4s v1.4.0

---

project/plugins.sbt

Bump `sbt-devoops` to `3.2.1`

---

build.sbt

Close #440: Bump `extras` to `0.47.0`

Close #440: Bump `extras` to `0.47.0`

---

changelogs/1.5.0.md

* Bump `extras` to `0.47.0` (#440)
***
* Add `time` types (#441)
Add
- `Month`
- `Day`
- `Hour`
- `Minute`
- `Second`
- `Millis`
***
* Make the type parameters of `Newtype` and `Refined` `specialized` (#444)
- `CanBeOrdered`
- `InlinedRefined`
- `Newtype`
- `NewtypeBase`
- `Refined`
- `RefinedBase`
- `types/numeric`
- `Numeric`
- `InlinedNumeric`
- `Min`
- `Max`
- `MinMax`

refined4s v1.5.0

---

build.sbt

Add `coverageEnabled := false` to Native projects

Add `coverageEnabled := false` to Native projects

---

.github/workflows/release.yml

Update GitHub Actions: Remove `test_report` from `release.yml`

Update GitHub Actions: Remove `test_report` from `release.yml`

---

changelogs/1.6.0.md

* Add Scala Native support for multiple modules (#449)
- `refined4s-cats`
- `refined4s-circe`
- `refined4s-extras-render`
- `refined4s-refined-compat-scala2`
- `refined4s-refined-compat-scala3`

refined4s v1.6.0

---

changelogs/1.7.0.md

* [`refined4s-chimney`] Support Scala Native (#456)

refined4s v1.7.0

---

README.md
docs/latest/intro.md

Update docs: Clean up

---

project/build.properties

Bump sbt to `1.11.4`

---

modules/refined4s-cats/shared/src/test/scala/refined4s/modules/cats/derivation/types/allSpec.scala

Close #486: [`refined4s-cats`] Add not-equal tests for `Eq` instances for the types in `refined4s.types`

Close #486: [`refined4s-cats`] Add not-equal tests for `Eq` instances for the types in `refined4s.types`

---

modules/refined4s-doobie-ce3/shared/src/main/scala/refined4s/modules/doobie/derivation/types/all.scala
modules/refined4s-doobie-ce3/shared/src/main/scala/refined4s/modules/doobie/derivation/types/time.scala
modules/refined4s-doobie-ce3/shared/src/test/scala/refined4s/modules/doobie/derivation/types/allSpec.scala
modules/refined4s-doobie-ce3/shared/src/test/scala/refined4s/modules/doobie/derivation/types/timeSpec.scala

Close #503: [`refined4s-doobie-ce3`] Add `Get` and `Put` type-class instances for `refined4s.types.time` types

Close #503: [`refined4s-doobie-ce3`] Add `Get` and `Put` type-class instances for `refined4s.types.time` types

---

project/build.properties

Bump sbt to 1.11.5

---

modules/refined4s-core/js/src/main/scala/refined4s/types/networkCompat.scala
modules/refined4s-core/jvm/src/main/scala/refined4s/types/networkCompat.scala
modules/refined4s-core/native/src/main/scala/refined4s/types/networkCompat.scala
modules/refined4s-core/shared/src/main/scala/refined4s/types/UriValidator.scala
modules/test-refined4s-core-without-cats/js/src/test/scala/refined4s/types/networkCompatSpec.scala
modules/test-refined4s-core-without-cats/jvm/src/test/scala/refined4s/types/networkCompatSpec.scala
modules/test-refined4s-core-without-cats/native/src/test/scala/refined4s/types/networkCompatSpec.scala
modules/test-refined4s-core-without-cats/shared/src/test/scala/refined4s/types/networkSpec.scala

Close #539: [`refined4s-core`] Add better error messages for `Uri` and `Url`

Close #539: [`refined4s-core`] Add better error messages for `Uri` and `Url`
