kevin-lee/refined4s

modules/refined4s-core/shared/src/main/scala/refined4s/Refined.scala
modules/refined4s-core/shared/src/main/scala/refined4s/RefinedBase.scala

Close #30 - Extract the essential properties of `Refined` and create `RefinedBase`

Close #30 - Extract the essential properties of `Refined` and create `RefinedBase`

---

.scalafix-scala3.conf
modules/refined4s-core/shared/src/main/scala/refined4s/InlinedRefined.scala
modules/refined4s-core/shared/src/test/scala/refined4s/InlinedRefinedSpec.scala
modules/refined4s-core/shared/src/test/scala/refined4s/InlinedRefinedType.scala

Close #32 - Add `InlinedRefined`

Close #32 - Add `InlinedRefined`

---

modules/refined4s-core/shared/src/main/scala/refined4s/Coercible.scala
modules/refined4s-core/shared/src/test/scala/refined4s/CoercibleSpec.scala

Close #42 - Add `Coercible` to type-safely cast refined type to the actual type

Close #42 - Add `Coercible` to type-safely cast refined type to the actual type

---

modules/refined4s-core/shared/src/main/scala/refined4s/RefinedCtor.scala
modules/refined4s-core/shared/src/test/scala/refined4s/RefinedCtorSpec.scala

Close #49 - Add `RefinedCtor[T, A]` to provide a way to create a validated type `T` from an actual type `A` with validation

Close #49 - Add `RefinedCtor[T, A]` to provide a way to create a validated type `T` from an actual type `A` with validation

---

build.sbt
modules/refined4s-core/shared/src/main/scala/refined4s/syntax.scala
modules/refined4s-core/shared/src/test/scala/refined4s/syntaxSpec.scala

Close #53 - Add `A.refinedTo[T]` syntax to create `Refined[A]` and `InlinedRefined[A]`

Close #53 - Add `A.refinedTo[T]` syntax to create `Refined[A]` and `InlinedRefined[A]`

---

modules/refined4s-core/shared/src/main/scala/refined4s/syntax.scala
modules/refined4s-core/shared/src/test/scala/refined4s/syntaxSpec.scala

Close #55 - Add `T.coerce[A]` syntax to easily get the value `A` from `Refined[A]#Type` and `InlinedRefined[A]#Type`

Close #55 - Add `T.coerce[A]` syntax to easily get the value `A` from `Refined[A]#Type` and `InlinedRefined[A]#Type`

---

build.sbt
modules/refined4s-cats/shared/src/main/scala/refined4s/cats/syntax.scala
modules/refined4s-cats/shared/src/test/scala/refined4s/cats/syntaxSpec.scala

Close #59 - Add `refined4s-cats` module and add `validateAs` syntax to create `Newtype` containing `Refined[A]` or `InlinedRefined[A]`

Close #59 - Add `refined4s-cats` module and add `validateAs` syntax to create `Newtype` containing `Refined[A]` or `InlinedRefined[A]`

---

modules/refined4s-core/shared/src/main/scala/refined4s/numeric.scala

Close #65 - Use `deriving` for `numericOrdering: Ordering[Type]` in `Numeric[A]`

Close #65 - Use `deriving` for `numericOrdering: Ordering[Type]` in `Numeric[A]`

---

modules/refined4s-core/shared/src/main/scala/refined4s/numeric.scala
modules/refined4s-core/shared/src/test/scala/refined4s/numericSpec.scala

Close #76 - [core] Add `NegDouble`, `NonNegDouble`, `PosDouble` and `NonPosDouble` to `numeric` package

Close #76 - [core] Add NegDouble, NonNegDouble, PosDouble and NonPosDouble to numeric package

---

changelogs/0.1.0.md

A trait `Refined[A]` should provide a way to create a refined type with validation.
It should also provide a way to validate in compile-time if applicable.
So it should be able to do like this.
```scala 3
type NonEmptyString = NonEmptyString.Type
object NonEmptyString extends Refined[String] {
inline override def predicate(a: String): Boolean = a != ""
}
NonEmptyString("Blah") // It compiles
NonEmptyString("") // A compile-time error
NonEmptyString.from("Blah") // Either[String, NonEmptyString] = Right(NonEmptyString("Blah"))
NonEmptyString.from("") // Either[String, NonEmptyString] = Left("Invalid value: ")
NonEmptyString.unsafeFrom("Blah") // NonEmptyString = NonEmptyString("Blah")
NonEmptyString.unsafeFrom("") // IllegalArgumentException
```
***
```scala 3
NonEmptyString("blah") // …
```

refined4s v0.1.0

---

.github/workflows/release.yml

Update: GitHub Actions - `release.yml`: Scala version for test coverage from 3.2.2 to 3.3.1

Update: GitHub Actions - `release.yml`: Scala version for test coverage from 3.2.2 to 3.3.1

---

.github/workflows/release.yml

GitHub Actions - `release.yml`: Remove `devOopsGitHubReleaseUploadArtifacts` to avoid uploading the artifacts to GitHub Release

GitHub Actions - `release.yml`: Remove `devOopsGitHubReleaseUploadArtifacts` to avoid uploading the artifacts to GitHub Release

---

changelogs/0.2.0.md

* Rename `refined4s.cats` to `refined4s.modules.cats` (#94)
```scala 3
import refined4s.modules.cats.derivation.*
import refined4s.modules.cats.syntax.*
```
* Add `Eq[A]` and `Show[A]` instances for the existing refined types (#95)
So with
```scala 3
import refined4s.modules.cats.derivation.instances.given
```
`Eq` and `Show` instances for the following types are available
* `NegInt`
* `NonNegInt`
* `PosInt`
* `NonPosInt`
* `NegLong`
* `NonNegLong`
* `PosLong`
* `NonPosLong`
* `NegShort`
* `NonNegShort`
* `PosShort`
* `NonPosShort`
* `NegByte`
* `NonNegByte`
* `PosByte`
* `NonPosByte`
* `NegFloat`
* `NonNegFloat`
* `PosFloat`
* `NonPosFloat`
* `NegDouble`
* `NonNegDouble`
* `PosDouble`
* `NonPosDouble`
* `NegBigInt`
* `NonNegBigInt`
* `PosBigInt`
* `NonPosBigInt`
* `NegBigDecimal`
* …

refined4s v0.2.0

---

changelogs/0.3.0.md

* [`refined4s-cats`] Replace `Eq` and `Show` instances for the existing refined types with the ones derived from the actual types using `Coercible` (#107)
* Add `refined4s-circe` module to support [circe](https://github.com/circe/circe) (#101)
* [`refined4s-circe`] Add `Encoder` and `Decoder`s for `Newtype`, `Refined` and `InlinedRefined` with `Coercible` and `RefinedCtor` (#103)
* [`refined4s-circe`] Add `CirceEncoder`, `CirceNewtypeDecoder`, `CirceRefinedDecoder`, `CirceNewtypeCodec` and `CirceRefinedCodec` to have circe `Encoder` and `Decoder` derived from the actual type for `Newtype`, `Refined` and `InlinedRefined` (#104)
```scala 3
import refined4s.modules.circe.derivation.*
```
```scala 3
type MyNewtype = MyNewtype.Type
object MyNewtype extends Newtype[String] with …
```

refined4s v0.3.0

---

build.sbt

Close #123 - Add `refined4s-doobie-ce2` and `refined4s-doobie-ce3` modules to support doobie

Close #123 - Add `refined4s-doobie-ce2` and `refined4s-doobie-ce3` modules to support doobie

---

changelogs/0.4.0.md

* Add `refined4s-doobie-ce2` and `refined4s-doobie-ce3` modules to support [doobie](https://github.com/tpolecat/doobie) (#123)
* [`refined4s-doobie`] Add `Get`s and `Put` for `Newtype`, `Refined` and `InlinedRefined` with `Coercible` and `RefinedCtor` (#124)
* [`refined4s-doobie`] Add `DoobiePut`, `DoobieNewtypeGet`, `DoobieRefinedGet`, `DoobieNewtypeGetPut` and `DoobieRefinedGetPut` to have circe `Get` and `Put` derived from the actual type for `Newtype`, `Refined` and `InlinedRefined` (#127)

refined4s v0.4.0

---

docs/core/_category_.json
docs/core/core.md
docs/core/newtype/_category_.json
docs/core/newtype/newtype.md

Update docs: add `core.md` and `newtype.md` - `refined4s-core` and `Newtype`

Update docs: add `core.md` and `newtype.md` - `refined4s-core` and `Newtype`

---

modules/refined4s-core/shared/src/main/scala/refined4s/types/numeric.scala

Close #146 - Add missing `inline` to `invalidReason` in the sub-types of `InlinedNumeric`

Close #146 - Add missing `inline` to `invalidReason` in the sub-types of `InlinedNumeric`

---

modules/refined4s-cats/shared/src/main/scala/refined4s/modules/cats/derivation/instances.scala

Close #152 - [`refined4s-core`] Add `contraCoercible` to `F[B] => F[A]` with `Contravariant[F]` and `Coercible[A, B]`
- Now `eqDerived` and `showDerived` use `contraCoercible`

Close #152 - [`refined4s-core`] Add `contraCoercible` to `F[B] => F[A]` with `Contravariant[F]` and `Coercible[A, B]`

---

build.sbt
modules/refined4s-circe/shared/src/main/scala/refined4s/modules/circe/derivation/instances.scala

Close #154 - [`refined4s-circe`] Update `refined4s.modules.circe.derivation.instances.derivedEncoder` to use `contraCoercible` and make it `inline`

Close #154 - [`refined4s-circe`] Update `refined4s.modules.circe.derivation.instances.derivedEncoder` to use `contraCoercible` and make it `inline`

---

modules/refined4s-circe/shared/src/main/scala/refined4s/modules/circe/derivation/instances.scala
modules/refined4s-core/shared/src/main/scala/refined4s/Coercible.scala
modules/refined4s-core/shared/src/main/scala/refined4s/Newtype.scala
modules/refined4s-core/shared/src/main/scala/refined4s/NewtypeBase.scala
modules/refined4s-core/shared/src/main/scala/refined4s/RefinedBase.scala
modules/refined4s-core/shared/src/test/scala/refined4s/CoercibleSpec.scala
modules/refined4s-pureconfig/shared/src/main/scala/refined4s/modules/pureconfig/derivation/instances.scala

* `wrap` and `unwrap` suffixed with `M`: `M` to `TC` (type constructor)
* `wrap` and `unwrap` suffixed with `MOfM`: `MOfM` to `HKT` (higher-kinded type)
* `M[*]` to `F[*]`
* `M1[*]` to `F[*]` and `M2[*]` to `G[*]` e.g.) `M1[M2[A]]` to `F[G[A]]`

Close #160 - Rename `Coercible` methods and type parameters

---

changelogs/0.5.0.md

* [`refined4s-cats`] Add `contraCoercible` to `F[B] => F[A]` with `Contravariant[F]` and `Coercible[A, B]` (#152)
This is useful to derive type-class instances for `Newtype`, `Refined` and `InlinedRefined` from the type-class instances of the actual types.
e.g.)
```scala 3
import refined4s.modules.cats.derivation.instances.contraCoercible
inline given eqDerived[A, B](using coercible: Coercible[A, B], eqB: Eq[B]): Eq[A] =
contraCoercible(eqB)
inline given showDerived[A, B](using coercible: Coercible[A, B], showB: Show[B]): Show[A] =
contraCoercible(showB)
```
where `B` is the actual type and `A` could be a newtype or a refined type.
***
* Add missing `inline` to `invalidReason` in the sub-types of `InlinedNumeric` (#146)
***
* [`refined4s-pureconfig`] Add type name to the error message of …

refined4s v0.5.0

---

modules/refined4s-core/shared/src/main/scala/refined4s/types/network.scala
modules/refined4s-core/shared/src/main/scala/refined4s/types/numeric.scala
modules/refined4s-core/shared/src/main/scala/refined4s/types/strings.scala
modules/refined4s-core/shared/src/test/scala/refined4s/types/networkGens.scala
modules/refined4s-core/shared/src/test/scala/refined4s/types/networkSpec.scala
modules/refined4s-core/shared/src/test/scala/refined4s/types/numericSpec.scala
modules/refined4s-core/shared/src/test/scala/refined4s/types/stringsSpec.scala

Close #168 - [`refined4s-core`] Keep only `all` `object` for pre-defined types and remove all the others

Close #168 - [`refined4s-core`] Keep only `all` `object` for pre-defined types and remove all the others

---

changelogs/0.6.0.md

* All modules: importing `derivation.instances.given` can cause an issue as it overrides all type-classes defined in the companion objects (#163)
* [`refined4s-cats`] Add explicit `Eq` and `Show` for pre-defined types (#171)
- Now it has `refined4s.modules.cats.derivation.types.all` for the all pre-defined types (e.g. `NegInt`, `PosInt`, `NonEmptyString`, etc.)
- `refined4s.modules.cats.derivation.instances` => `refined4s.modules.cats.derivation.generic.auto`
- `refined4s.modules.cats.derivation.instances.contraCoercible` is moved to `refined4s.modules.cats.syntax`
* [`refined4s-circe`] Add explicit `Encoder` and `Decoder` for pre-defined types (#166)
* [`refined4s-pureconfig`] Add explicit `ConfigReader` and `ConfigWriter` for pre-defined types (#172)
* [`refined4s-doobie`] Add explicit …

refined4s v0.6.0

---

modules/refined4s-cats/shared/src/main/scala/refined4s/modules/cats/syntax.scala
modules/refined4s-cats/shared/src/test/scala/refined4s/modules/cats/syntaxSpec.scala

Close #182 - [`refined4s-cats`] Rename `validateAs` in `refined4s.modules.cats.syntax` to `refinedNewtypeNec`

Close #182 - [`refined4s-cats`] Rename `validateAs` in `refined4s.modules.cats.syntax` to `refinedNewtypeNec`

---

modules/refined4s-cats/shared/src/test/scala/refined4s/modules/cats/derivation/types/CatsWithCustomTypeClassesSpec.scala
modules/refined4s-core/shared/src/main/scala/refined4s/NewtypeBase.scala
modules/refined4s-core/shared/src/main/scala/refined4s/syntax.scala

Close #186 - [`refined4s-core`] Move `toValue` from `refined4s.syntax` to `refined4s.NewtypeBase`

Close #186 - [`refined4s-core`] Move `toValue` from `refined4s.syntax` to `refined4s.NewtypeBase`

---

modules/refined4s-cats/shared/src/main/scala/refined4s/modules/cats/syntax.scala
modules/refined4s-cats/shared/src/test/scala/refined4s/modules/cats/syntaxSpec.scala

Close #188 - [`refined4s-cats`] Add `validateAs` in `refined4s.modules.cats.syntax` to validate and return `Validated`

Close #188 - [`refined4s-cats`] Add `validateAs` in `refined4s.modules.cats.syntax` to validate and return `Validated`

---

modules/refined4s-cats/shared/src/main/scala/refined4s/modules/cats/syntax.scala
modules/refined4s-cats/shared/src/test/scala/refined4s/modules/cats/syntaxSpec.scala

Close #189 - [`refined4s-cats`] Add `validateNecAs` in `refined4s.modules.cats.syntax` to validate and return `ValidatedNec`

Close #189 - [`refined4s-cats`] Add `validateNecAs` in `refined4s.modules.cats.syntax` to validate and return `ValidatedNec`

---

modules/refined4s-cats/shared/src/main/scala/refined4s/modules/cats/derivation/generic/auto.scala
modules/refined4s-cats/shared/src/test/scala/refined4s/modules/cats/derivation/generic/autoSpec.scala

Close #194 - [`refined4s-cats`] Add `derivedOrder` to have the instance of `Order[A]` derived from `Coercible[A, B]` and `Order[B]`

Close #194 - [`refined4s-cats`] Add `derivedOrder` to have the instance of `Order[A]` derived from `Coercible[A, B]` and `Order[B]`

---

modules/refined4s-core/shared/src/main/scala/refined4s/CanBeOrdered.scala
modules/refined4s-core/shared/src/test/scala/refined4s/CanBeOrderedSpec.scala

Close #196 - [`refined4s-core`] Add `CanBeOrdered` for providing `Ordering` and `Conversion[Type, Ordered[Type]]`

Close #196 - [`refined4s-core`] Add `CanBeOrdered` for providing `Ordering` and `Conversion[Type, Ordered[Type]]`

---

modules/refined4s-core/shared/src/main/scala/refined4s/types/numeric.scala

Close #199 - [`refined4s-core`] Replace `Ordering` and `Conversion[Type, Ordered[Type]]` for numeric types with `CanBeOrdered`

Close #199 - [`refined4s-core`] Replace `Ordering` and `Conversion[Type, Ordered[Type]]` for numeric types with `CanBeOrdered`

---

changelogs/0.7.0.md

* [`refined4s-cats`] Rename `validateAs` in `refined4s.modules.cats.syntax` to `refinedNewtypeNec` (#182)
***
* [`refined4s-core`] Move `toValue` from `refined4s.syntax` to `refined4s.NewtypeBase` (#186)
So with the given following code,
```scala 3
import refined4s.*
import refined4s.types.all.*
object Name extends Newtype[NonEmptyString]
```
the following is possible without importing any `syntax`.
```scala 3
val name = Name(NonEmptyString("Kevin"))
name.toValue
// String = "Kevin"
```
***
* [`refined4s-cats`] Add `refinedNewtypeNel` in `refined4s.modules.cats.syntax` (#184)
```scala 3
import refined4s.*
import refined4s.types.all.*
import refined4s.modules.cats.syntax.*
object Name extends Newtype[NonEmptyString] …
```

refined4s v0.7.0

---

modules/refined4s-core/shared/src/main/scala/refined4s/Newtype.scala
modules/refined4s-core/shared/src/main/scala/refined4s/RefinedBase.scala

Close #208 - [`refined4s-core`] Change `NewtypeBase.unapply` and `RefinedBase.unapply` to return `Some[A]` instead of `Option[A]`

Close #208 - [`refined4s-core`] Change `NewtypeBase.unapply` and `RefinedBase.unapply` to return `Some[A]` instead of `Option[A]`

---

changelogs/0.8.0.md

* [`refined4s-core`] Change `NewtypeBase.unapply` and `RefinedBase.unapply` to return `Some[A]` instead of `Option[A]` (#208)
> The reason for having `Some[A]` as the return type of the `unapply` methods can be found at https://github.com/scala/bug/issues/12232. 😔

refined4s v0.8.0

---

changelogs/0.9.0.md

* Add `refined4s-extras-render` to support `Render` for `refined4s` (#215)
```scala 3
refined4s.modules.extras.derivation.ExtrasRender
refined4s.modules.extras.derivation.types.all.given
refined4s.modules.extras.derivation.generic.auto.given
```
e.g.)
```scala 3
import extras.render.Render
import refined4s.types.all.*
import refined4s.modules.extras.derivation.types.all.given
val name = NonEmptyString("Kevin")
Render[NonEmptyString].render(name)
// String = Kevin
```
```scala 3
import extras.render.Render
import refined4s.Newtype
import refined4s.modules.extras.derivation.ExtrasRender
object Name extends Newtype[String], ExtrasRender[String]
val name = Name("Kevin")
Render[Name].render(name)
// String = Kevin
```
```scala 3
import extras.render.Render
import …
```

refined4s v0.9.0

---

modules/refined4s-core/shared/src/main/scala/refined4s/types/numeric.scala

Close #225 - [`refined4s-core`] Move `Numeric` and `InlinedNumeric` from `numeric` trait to `numeric` object

Close #225 - [`refined4s-core`] Move `Numeric` and `InlinedNumeric` from `numeric` trait to `numeric` object

---

changelogs/0.11.0.md

* [`refined4s-core`] Add `MinValue` and `MaxValue` to refined basic numeric types (#223)
* Add `Min` trait
* Add `Max` trait
* Add `MinMax` trait
Add `MinMax` to the following types to have `MinValue` and `MaxValue`
* `NegInt`
* `NonNegInt`
* `PosInt`
* `NonPosInt`
* `NegLong`
* `NonNegLong`
* `PosLong`
* `NonPosLong`
* `NegShort`
* `NonNegShort`
* `PosShort`
* `NonPosShort`
* `NegByte`
* `NonNegByte`
* `PosByte`
* `NonPosByte`
* `NegFloat`
* `NonNegFloat`
* `PosFloat`
* `NonPosFloat`
* `NegDouble`
* `NonNegDouble`
* `PosDouble`
* `NonPosDouble`
* [`refined4s-core`] Move `Numeric` and `InlinedNumeric` from `numeric` trait to `numeric` object (#225)

refined4s v0.11.0

---

changelogs/0.12.0.md

* [`refined4s-core`] Make pre-defined types in `types.all` importable from each type category (i.e. `numeric`, `strings` and `network`) (#237)
So it means a type like `refined4s.types.numeric.NegInt` should be exactly the same as `refined4s.types.all.NegInt`.
***
* Add `refined4s-refined-compat` modules for compatibility with the `refined` library in Scala 2 (#241)
* `refined4s-refined-compat-scala2` for compatibility with `refined` in Scala 2
* `refined4s-refined-compat-scala3` for just using `refined4s` in Scala 3
***
* Add `RefinedCompatAllTypes` to `refined4s-refined-compat-scala2` and `refined4s-refined-compat-scala3` (#243)
* [`refined4s-core`] Move `MinValue` and `MaxValue` from each `MinMax` to `Min` and `Max` (#239)
e.g.)
```scala 3
type NegInt = NegInt.Type
object NegInt extends …
```

refined4s v0.12.0

---

modules/refined4s-tapir/shared/src/main/scala/refined4s/modules/tapir/derivation/TapirNewtypeSchema.scala
modules/refined4s-tapir/shared/src/main/scala/refined4s/modules/tapir/derivation/TapirRefinedSchema.scala
modules/refined4s-tapir/shared/src/test/scala/refined4s/modules/tapir/derivation/TapirSchemaSpec.scala

Close #273 - [`refined4s-tapir`] Add `TapirNewtypeSchema` and `TapirRefinedSchema` to support `sttp.tapir.Schema` for `refined4s`

Close #273 - [`refined4s-tapir`] Add `TapirNewtypeSchema` and `TapirRefinedSchema` to support `sttp.tapir.Schema` for `refined4s`

---

modules/refined4s-circe/shared/src/main/scala/refined4s/modules/circe/derivation/types/strings.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/generic/autoSpec.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/types/allSpec.scala

Close #284 - [`refined4s-circe`] Add `circe` support for `NonBlankString`

Close #284 - [`refined4s-circe`] Add `circe` support for `NonBlankString`

---

modules/refined4s-pureconfig/shared/src/test/scala/refined4s/modules/pureconfig/derivation/generic/autoSpec.scala

Add missing tests for `pureconfig` support with auto derivation

Add missing tests for `pureconfig` support with auto derivation

---

modules/refined4s-pureconfig/shared/src/main/scala/refined4s/modules/pureconfig/derivation/types/all.scala
modules/refined4s-pureconfig/shared/src/test/scala/refined4s/modules/pureconfig/derivation/generic/autoSpec.scala
modules/refined4s-pureconfig/shared/src/test/scala/refined4s/modules/pureconfig/derivation/types/allSpec.scala

Close #285 - [`refined4s-pureconfig`] Add `pureconfig` support for `NonBlankString`

Close #285 - [`refined4s-pureconfig`] Add `pureconfig` support for `NonBlankString`

---

website/docusaurus.config.ts

Update: Docusaurus config - add additionalLanguages to prism (`bash`, `diff` and `json`)

Update: Docusaurus config - add additionalLanguages to prism (`bash`, `diff` and `json`)

---

docs/core/refined/types.md

Update docs: Update `NonBlankString` in `types.md` to have more concatenation

Update docs: Update `NonBlankString` in `types.md` to have more concatenation

---

modules/refined4s-core/shared/src/main/scala/refined4s/types/strings.scala
modules/refined4s-core/shared/src/test/scala/refined4s/types/stringsSpec.scala

Close #312 - Add unicode encoding for the error message from `NonBlankString.from`

Close #312 - Add unicode encoding for the error message from `NonBlankString.from`

---

build.sbt

Bump libs in test
- effectie to 2.0.0-beta14
- embedded-postgres to 2.0.7
- logback to 1.5.6

Bump libs in test

---

modules/refined4s-circe/shared/src/main/scala/refined4s/modules/circe/derivation/types/network.scala
modules/refined4s-circe/shared/src/main/scala/refined4s/modules/circe/derivation/types/numeric.scala
modules/refined4s-circe/shared/src/main/scala/refined4s/modules/circe/derivation/types/strings.scala

Close #315 - [`refined4s-circe`] Add `numeric`, `strings` and `network` objects in `refined4s.modules.circe.derivation.types`

Close #315 - [refined4s-circe] Add numeric, strings and network objects in refined4s.modules.circe.derivation.types

---

changelogs/0.16.0.md

* [`refined4s-core`] Add unicode encoding for the error message from `NonBlankString.from` (#312)
```scala 3
val s = "\u0009\u200a\u2004\u1680"
// String = "	   "
NonBlankString.from(s)
// Left(Invalid value: [	   ], unicode=[\u0009\u200a\u2004\u1680]. It must be not all whitespace non-empty String)
```
* [`refined4s-circe`] Add `numeric`, `strings` and `network` objects in `refined4s.modules.circe.derivation.types`

refined4s v0.16.0

---

build.sbt

Bump Scala 2.13 for `refined-compat-scala2` to 2.13.13

Bump Scala 2.13 for `refined-compat-scala2` to 2.13.13

---

modules/refined4s-chimney/shared/src/main/scala/refined4s/modules/chimney/derivation/generic/auto.scala
modules/refined4s-chimney/shared/src/test/scala/refined4s/modules/chimney/derivation/generic/autoSpec.scala

Close #325 - [`refined4s-chimney`] Add `refined4s.modules.chimney.derivation.generic.auto` for auto derivation for Chimney

Close #325 - [`refined4s-chimney`] Add `refined4s.modules.chimney.derivation.generic.auto` for auto derivation for Chimney

---

changelogs/0.17.0.md

* Add a module to support [Chimney](https://github.com/scalalandio/chimney) (#320)
***
* [`refined4s-chimney`] Add `refined4s.modules.chimney.derivation.generic.auto` for auto derivation for Chimney (#325)
```scala 3
import io.scalaland.chimney
import refined4s.modules.chimney.derivation.generic.auto.given
import refined4s.types.all.PosInt
import refined4s.{Newtype, Refined}
val emailRegEx =
"""([a-zA-Z0-9]+([-_\.\+]+[a-zA-Z0-9]+)*@[a-zA-Z0-9]+([-_]+[a-zA-Z0-9]+)*(?:[.][a-zA-Z0-9]+([-_]+[a-zA-Z0-9]+)*)+)""".r
final case class Foo(id: Foo.Id, baz: Foo.Baz)
object Foo {
type Id = Id.Type
object Id extends Newtype[PosInt]
object Name extends Newtype[String]
type Email = Email.Type
object Email extends Refined[String] {
override def invalidReason(a: String): String = …
```

refined4s v0.17.0

---

modules/refined4s-circe/shared/src/main/scala/refined4s/modules/circe/derivation/types/network.scala
modules/refined4s-circe/shared/src/main/scala/refined4s/modules/circe/derivation/types/numeric.scala
modules/refined4s-circe/shared/src/main/scala/refined4s/modules/circe/derivation/types/strings.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/types/networkSpec.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/types/numericSpec.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/types/stringsSpec.scala

Close #361 - [`refined4s-circe`] Add `KeyEncoder` and `KeyDecoder` for pre-defined refined types

Close #361 - [`refined4s-circe`] Add `KeyEncoder` and `KeyDecoder` for pre-defined refined types

---

build.sbt

Close #373 - Add compile-time `javaOptions` to improve build

Close #373 - Add compile-time `javaOptions` to improve build

---

build.sbt
modules/refined4s-core/shared/src/test/scala/refined4s/InlinedRefinedSpec.scala
modules/refined4s-core/shared/src/test/scala/refined4s/InlinedRefinedType.scala
modules/refined4s-core/shared/src/test/scala/refined4s/RefinedSpec.scala
modules/refined4s-core/shared/src/test/scala/refined4s/types/networkSpec.scala
modules/refined4s-core/shared/src/test/scala/refined4s/types/numericSpec.scala
modules/refined4s-core/shared/src/test/scala/refined4s/types/stringsSpec.scala
project/plugins.sbt

Close #372 - Update sbt plugins
* `sbt-ci-release` to `1.6.1`
* `sbt-wartremover` to `3.2.0`
* `sbt-scalafix` to `0.12.1`
* `sbt-scalafmt` to `2.5.2`
* `sbt-scoverage` to `2.1.1`
* `sbt-mdoc` to `2.5.4`
* `sbt-docusaur` to `0.16.0`
* `sbt-tpolecat` to `0.5.2`
* `com.github.xuwei-k:scalafix-rules` to `0.4.5`

Close #372 - Update sbt plugins

---

changelogs/0.19.0.md

* [`refined4s-circe`] Add `KeyEncoder`, `KeyDecoder` and `KeyCodec` for `Newtype` and `Refined` (#355)
***
* [`refined4s-core`] Add `toUrl` to `Uri`, and add `toUri` to `toUrl` (#356)
```scala 3
Uri("https://www.google.com").toUrl
// Url("https://www.google.com")
Url("https://www.google.com").toUri
// Uri("https://www.google.com")
```
***
* [`refined4s-core`] Add `toURL` to `Uri`, and add `toURI` to `toUrl` (#358)
```scala 3
Uri("https://www.google.com").toURL
// java.net.URL("https://www.google.com")
Url("https://www.google.com").toURI
// java.net.URI("https://www.google.com")
```
***
* [`refined4s-circe`] Add `KeyEncoder` and `KeyDecoder` for pre-defined refined types (#361)
***
* [`refined4s-circe`] Add `KeyEncoder` and `KeyDecoder` to `refined4s.modules.circe.derivation.generic.auto` …

refined4s v0.19.0

---

build.sbt
modules/refined4s-circe/js/src/test/scala/refined4s/modules/circe/derivation/types/NumericTestValues.scala
modules/refined4s-circe/jvm/src/test/scala/refined4s/modules/circe/derivation/types/NumericTestValues.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/generic/numericSpec.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/types/CirceCodecWithTypeClassesForTypesSpec.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/types/numericSpec.scala
modules/refined4s-core/js/src/main/scala/refined4s/types/networkCompat.scala
modules/refined4s-core/js/src/test/scala/refined4s/types/networkCompatSpec.scala
modules/refined4s-core/jvm/src/main/scala/refined4s/types/networkCompat.scala
modules/refined4s-core/jvm/src/test/scala/refined4s/types/networkCompatSpec.scala
modules/refined4s-core/shared/src/main/scala/refined4s/types/network.scala
modules/refined4s-core/shared/src/test/scala/refined4s/types/networkSpec.scala
modules/refined4s-pureconfig/shared/src/test/scala/refined4s/modules/pureconfig/derivation/generic/autoSpec.scala
project/plugins.sbt

Fix #370 - Scala.js support is broken
Add
- `scalajs-java-securerandom` to use `java.security.SecureRandom` for `java.util.UUID`
- `scala-java-time` for `java.time` for Scala.js
- a custom URL for Scala.js because there's no alternative to `java.net.URL`
Also make some necessary changes including removing the code that won't be available in JavaScript.
Fix the tests for JavaScript. There are some issues with `Long` and `BigInt` less than -9007199254740991L and greater than 9007199254740991L.

Fix #370 - Scala.js support is broken

---

changelogs/1.0.0.md

* Fix: Scala.js support is broken (#370)
To fix it, the following changes were made:
* Added
* `scalajs-java-securerandom` to use `java.security.SecureRandom` for `java.util.UUID`
* `scala-java-time` for `java.time` in Scala.js
* a custom URL implementation for Scala.js because there's no alternative to `java.net.URL`
* Made other necessary changes, including removing code unavailable in JavaScript.
* Fixed the tests for JavaScript. There were issues with `Long` and `BigInt` values less than `-9007199254740991L` and greater than `9007199254740991L`.

refined4s v1.0.0

---

.github/workflows/doc-site-build-only.yml
.github/workflows/doc-site-publish.yml

Update GitHub Actions workflows for the doc site build: Bump Node to 22.17.0

Update GitHub Actions workflows for the doc site build: Bump Node to 22.17.0

---

changelogs/1.2.0.md

* Bump Scala to `3.3.5` (#419)
* [`refined4s-refined-compat-scala2`] Bump Scala 2 versions (#421)
- Upgrade Scala versions in `refinedCompatScala2` (`refined4s-refined-compat-scala2`) module:
- `2.12.16` -> `2.12.18`
- `2.13.13` -> `2.13.15`
- Exclude `scala-xml` dependency from `refined` library to avoid conflicts
* Bump extras to `0.45.0` (#423)
* Disable Scala.js because `extras-type-info` used by `refined4s` doesn't support Scala.js anymore (since `0.45.0`) (#426)
* Bump sbt to `1.11.3` (#428)

refined4s v1.2.0

---

changelogs/1.3.0.md

* Bump extras to `0.46.1` (#424)

refined4s v1.3.0

---

modules/refined4s-core/shared/src/main/scala/refined4s/CanBeOrdered.scala
modules/refined4s-core/shared/src/main/scala/refined4s/InlinedRefined.scala
modules/refined4s-core/shared/src/main/scala/refined4s/Newtype.scala
modules/refined4s-core/shared/src/main/scala/refined4s/NewtypeBase.scala
modules/refined4s-core/shared/src/main/scala/refined4s/Refined.scala
modules/refined4s-core/shared/src/main/scala/refined4s/RefinedBase.scala
modules/refined4s-core/shared/src/main/scala/refined4s/types/numeric.scala

Close #444: Make the type parameters of `Newtype` and `Refined` `specialized`
Specialize generic type parameters across core and numeric traits to reduce boxing when instantiated with primitive types.
Using Scala's `@specialized` to avoid boxing/unboxing and reduce allocations for `Int`, `Long`, `Short`, `Byte`, `Float`, and `Double` improves hot-path performance, especially for operations on refined/newtype values.
This change is annotation-only with no source-level API changes. Runtime semantics remain the same; only performance characteristics may improve.
Changes:
- `trait CanBeOrdered[@specialized(Int, Long, Short, Byte, Float, Double) A: Ordering]`
- `trait InlinedRefined[@specialized A]`
- `trait Newtype[@specialized A]`
- `trait NewtypeBase[@specialized A]`
- `trait …

Close #444: Make the type parameters of `Newtype` and `Refined` `specialized`

---

.github/workflows/build.yml
.github/workflows/checks.yml
.github/workflows/coverage.yml
.github/workflows/doc-site-build-only.yml
.github/workflows/doc-site-publish.yml
.github/workflows/release.yml

- Remove version pin from `actions/setup-java` to use latest `v5` across all workflows

Update GitHub Actions to use `actions/setup-java@v5`

---

modules/refined4s-cats/shared/src/main/scala/refined4s/modules/cats/derivation/types/all.scala
modules/refined4s-cats/shared/src/test/scala/refined4s/modules/cats/derivation/types/CatsWithCustomTypeClassesSpec.scala
modules/refined4s-cats/shared/src/test/scala/refined4s/modules/cats/derivation/types/allSpec.scala
modules/refined4s-core/shared/src/main/scala/refined4s/types/numeric.scala
modules/test-refined4s-core-without-cats/shared/src/test/scala/refined4s/types/numericSpec.scala

- Move `Eq` and `Show` type class instances for `refined4s.types.numeric` types from `refined4s-cats` to `refined4s-core` then
- Generalize derived instances for refined `numeric` types from concrete `cats.Eq`/`cats.Show` given instances to polymorphic givens constrained by `CatsEq`/`CatsShow`, decoupling the `core` API surface from `cats` while keeping derivation possible if `cats` is available on the classpath (i.e., added via sbt `libraryDependencies`).

Close #465: Move `Eq` and `Show` type class instances for `refined4s.types.numeric` types from `refined4s-cats` to `refined4s-core` with `orphan-cats`

---

modules/test-refined4s-core-without-cats/shared/src/test/scala/refined4s/types/networkWithoutCatsSpec.scala
modules/test-refined4s-core-without-cats/shared/src/test/scala/refined4s/types/numericWithoutCatsSpec.scala
modules/test-refined4s-core-without-cats/shared/src/test/scala/refined4s/types/stringsWithoutCatsSpec.scala

Close #473: [`test-refined4s-core-without-cats`] Rename tests for `cats` type class instances of `refined4s.types.all` without `cats`

Close #473: [`test-refined4s-core-without-cats`] Rename tests for `cats` type class instances of `refined4s.types.all` without `cats`

---

modules/refined4s-cats/shared/src/test/scala/refined4s/modules/cats/derivation/types/allSpec.scala
modules/refined4s-core/shared/src/main/scala/refined4s/types/time.scala
modules/test-refined4s-core-without-cats/shared/src/test/scala/refined4s/types/allSpec.scala
modules/test-refined4s-core-without-cats/shared/src/test/scala/refined4s/types/timeWithoutCatsSpec.scala

Close #476: Move `Eq` and `Show` type class instances for `refined4s.types.time` types from `refined4s-cats` to `refined4s-core` with `orphan-cats`

Close #476: Move `Eq` and `Show` type class instances for `refined4s.types.time` types from `refined4s-cats` to `refined4s-core` with `orphan-cats`

---

build.sbt
modules/refined4s-cats/shared/src/test/scala/refined4s/modules/cats/derivation/types/allSpec.scala
modules/refined4s-core/shared/src/main/scala/refined4s/types/strings.scala
modules/test-refined4s-core-without-cats/shared/src/test/scala/refined4s/ExpectedErrorMessages.scala
modules/test-refined4s-core-without-cats/shared/src/test/scala/refined4s/types/stringsWithoutCatsSpec.scala

- core: Add derived cats `Hash` instances for
- `NonEmptyString`
- `NonBlankString`
- `Uuid`
via `internalDef.contraCoercible` with explicit type params.
- Refactor cats type class instances for `strings`, restructuring them into hierarchical traits to resolve ambiguous `Eq` and `Hash` instances.
- Add `Hash` tests for all string types
- tests with cats: Add property tests asserting `hash` and `##` match the underlying string's `hashCode` for `NonEmptyString`, `NonBlankString` and `Uuid`.
- tests without cats: Add expected compile-time failures for missing `Hash` instances
- Add missing Hash error message tests for builds without cats dependencies.
- Add `-explain` to Scala 3 `scalacOptions` for better error messages.

Close #488: [`refined4s-core`] Add `cats.Hash` type class instances for `refined4s.types.strings` with `orphan-cats`

---

modules/refined4s-cats/shared/src/test/scala/refined4s/modules/cats/derivation/types/allSpec.scala
modules/refined4s-core/js/src/main/scala/refined4s/types/networkCompat.scala
modules/refined4s-core/jvm/src/main/scala/refined4s/types/networkCompat.scala
modules/refined4s-core/native/src/main/scala/refined4s/types/networkCompat.scala
modules/refined4s-core/shared/src/main/scala/refined4s/types/network.scala
modules/test-refined4s-core-without-cats/shared/src/test/scala/refined4s/types/networkWithoutCatsSpec.scala

- Core: Add derived `cats.Hash` instances for `network` types:
- `Uri`
- `Url`
- `PortNumber`
- `SystemPortNumber`
- `NonSystemPortNumber`
- `UserPortNumber`
- `DynamicPortNumber`
- Refactor cats type class instances for `network`, restructuring them into hierarchical traits to resolve ambiguous `Eq` and `Hash` instances.
- Tests with cats: Add `Hash` property tests for `Uri`, `Url`, and all port number variants. Verify `.hash` and `##` delegate to underlying value `hashCode`.
- Tests without cats: Assert `derived*Hash` is not available without `cats` for all `network` types (also add `dynamicPortNumberSpec`).

Close #490: [`refined4s-core`] Add `cats.Hash` type class instances for `refined4s.types.network` with `orphan-cats`

---

modules/refined4s-cats/shared/src/test/scala/refined4s/modules/cats/derivation/types/allSpec.scala
modules/refined4s-core/shared/src/main/scala/refined4s/types/time.scala
modules/test-refined4s-core-without-cats/shared/src/test/scala/refined4s/types/timeWithoutCatsSpec.scala

- Add `Hash` type class instances for `Month`, `Day`, `Hour`, `Minute`, `Second` and `Millis` types.
- Add comprehensive `Hash` tests for all `time` types

Close #492: [`refined4s-core`] Add `cats.Hash` type class instances for `refined4s.types.time` with `orphan-cats`

---

project/plugins.sbt

Bump sbt plugins
- `sbt-ci-release`: `1.11.1` -> `1.11.2`
- `sbt-scalafix`: `0.12.1` -> `0.14.3`
- `sbt-scalafmt`: `2.5.2` -> `2.5.5`
- `sbt-mdoc`: `2.5.4` -> `2.7.2`
- `sbt-docusaur`: `0.16.0` -> `0.17.0`

Bump sbt plugins

---

modules/refined4s-cats/shared/src/test/scala/refined4s/modules/cats/derivation/types/allSpec.scala
modules/refined4s-core/shared/src/main/scala/refined4s/types/numeric.scala
modules/test-refined4s-core-without-cats/shared/src/test/scala/refined4s/types/numericWithoutCatsSpec.scala

- Add `Hash` typeclass instances for all `numeric` refined types
- Add test for `Hash` for all numeric types (Int, Long, BigInt, BigDecimal variants)
- Refactor cats type class instances for `numeric`, restructuring them into hierarchical traits to resolve ambiguous `Eq` and `Hash` instances.

Close #491: [`refined4s-core`] Add `cats.Hash` type class instances for `refined4s.types.numeric` with `orphan-cats`

---

modules/refined4s-circe/shared/src/main/scala/refined4s/modules/circe/derivation/types/all.scala
modules/refined4s-circe/shared/src/main/scala/refined4s/modules/circe/derivation/types/time.scala
modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/types/timeSpec.scala

Close #497: [`refined4s-circe`] Add `Encoder`, `Decoder`, `KeyEncoder` and `KeyDecoder` type-class instances for `refined4s.types.time` types

Close #497: [`refined4s-circe`] Add `Encoder`, `Decoder`, `KeyEncoder` and `KeyDecoder` type-class instances for `refined4s.types.time` types

---

modules/refined4s-pureconfig/shared/src/main/scala/refined4s/modules/pureconfig/derivation/types/all.scala
modules/refined4s-pureconfig/shared/src/main/scala/refined4s/modules/pureconfig/derivation/types/internalDef.scala
modules/refined4s-pureconfig/shared/src/main/scala/refined4s/modules/pureconfig/derivation/types/time.scala
modules/refined4s-pureconfig/shared/src/test/scala/refined4s/modules/pureconfig/derivation/types/allSpec.scala
modules/refined4s-pureconfig/shared/src/test/scala/refined4s/modules/pureconfig/derivation/types/timeSpec.scala
modules/test-refined4s-core-without-cats/shared/src/test/scala/refined4s/types/TimeGens.scala

- Also update `TimeGens` for testing

Close #501: [`refined4s-pureconfig`] Add `ConfigReader` and `ConfigWriter` type-class instances for `refined4s.types.time` types

---

modules/refined4s-cats/shared/src/main/scala/refined4s/modules/cats/derivation/CatsHash.scala
modules/refined4s-cats/shared/src/test/scala/refined4s/modules/cats/derivation/CatsHashSpec.scala

Close #508: [`refined4s-cats`] Add `CatsHash` to derive `Hash` from the actual type's `Hash`

Close #508: [`refined4s-cats`] Add `CatsHash` to derive `Hash` from the actual type's `Hash`

---

modules/refined4s-core/jvm/src/main/scala/refined4s/types/networkCompat.scala

Close #535: Use the `java.net.URL` constructor for `Url` again

Close #535: Use the `java.net.URL` constructor for `Url` again
